[package]
name = "refren"
version = "0.1.0"
authors = ["Bartosz Marcinkowski <bm371613@gmail.com>"]
description = "A language agnostic, code-style aware, refactoring/renaming tool."

[dependencies]
clap = "2.32.0"
